#pragma once

#include "phc.hpp"

// MUTATO,C,6	SZEMSZAM,C,11	NEV,C,30	ORSZAG,C,3	IR_SZAM,C,5	UT,C,30	MEGJ_JELZ,L	MEGJ,M	MOD_DAT	TIPUS_JELZ,L	TULTIP,N,1,0	KONYVVEZ,N,1,0	TARSASAG,N,2,0	ERV_ATIPUS,C,2	AKT_ATIPUS,C,2	AGAZAT,C,2	ERTKOD,C,3	SZULDAT,D	K_AZON,C,2	JEL1,C,2	JEL2,C,2	JEL3,C,2	JEL4,C,2	ALLKOD,C,3	CSOPMEGJEL,L	TORLOKA,C,3	KOVTRANZ,N,5,0	HELYSEG,C,25	LEVORSZAG,C,3	LEVIR_SZAM,C,5	LEVUT,C,30	NEV_PTR,C,25	CIM_PTR,C,25	LEVCIM_PTR,C,25	ELUGY,L
// 	JEL2,C,2	JEL3,C,2	JEL4,C,2	ALLKOD,C,3	CSOPMEGJEL,L	TORLOKA,C,3	KOVTRANZ,N,5,0	HELYSEG,C,25	LEVORSZAG,C,3	LEVIR_SZAM,C,5	LEVUT,C,30	NEV_PTR,C,25	CIM_PTR,C,25	LEVCIM_PTR,C,25	ELUGY,L

enum class s_tszem
{
    MUTATO,   // cegnév
    SZEMSZAM, //?
    NEV,          // IRSZ
    ORSZAG,   // Város
    IR_SZAM,    // utca
    UT,
    MEGJ_JELZ,  // datum
    MEGJ, // datum
    MOD_DAT,
    TIPUS_JELZ,
    TULTIP,
    KONYVVEZ,
    TARSASAG,
    ERV_ATIPUS,
    AKT_ATIPUS,
    AGAZAT, // datum
    ERTKOD,
    SZULDAT,
    K_AZON,
    JEL1,
    JEL2,
    JEL3,
    JEL4,
    ALLKOD,
    CSOPMEGJEL,
    TORLOKA,
    KOVTRANZ,
    HELYSEG,
    LEVORSZAG,
    LEVIR_SZAM,
    LEVUT,
    NEV_PTR,
    CIM_PTR,
    LEVCIM_PTR,
    ELUGY,
};
