#pragma once

#include <phc.hpp>

// NEV,C,129	VAROS,C,30	UTCA,C,30	ADOSZ,C,13	IRSZ,C,4	KDAT,D	VDAT,D	UJ,L	RDAT,D	MDAT,D	CSODTIP,C,2	HSZAM,C,16	RKOD,C,6	RIDO,C,10	MODOSIT,L	JEGYZ,C,10	BIRHAT,C,25	BIRSZLSZ,C,24	BIRDAT,D	BIRO,C,60	FNEV,C,60	FIRSZ,C,4	FVAROS,C,30	FCIM,C,30	REKORD,N,10,0

enum class s_uj
{
    NEV, // Cegnev
    VAROS,
    UTCA,
    ADOSZ,
    IRSZ,
    KDAT,
    VDAT,
    UJ,
    RDAT,
    MDAT,
    CSODTIP,
    HSZAM,
    RKOD,
    RIDO,
    MODOSIT,
    JEGYZ,
    BIRHAT,
    BIRSZLSZ,
    BIRDAT,
    BIRO,
    FNEV,
    FIRSZ,
    FVAROS,
    FCIM,
    REKORD,
};
